### ISSUE TITLE
Sockinfo, ipinfo and interactions fail for 2605:E000:1F00:D3F1:0:0:0:0/64

### ISSUE THREAD

**Issue by Dreamy-Jazz** [roysmith/spi-tools#133]
Seemingly the tool can't handle ranges. I haven't tested G5, but the other links fail for 2605:E000:1F00:D3F1:0:0:0:0/64 regardless of whether I am logged in or not. It just returns a 500 server error and nothing else.

**Comment by roysmith** [comment]
Thanks for the note.  Which SPI were you running it on?

**Comment by Dreamy-Jazz** [comment]
Wikipedia:Sockpuppet investigations/2605:E000:1F00:D3F1:0:0:0:0/64

**Comment by Dreamy-Jazz** [comment]
First in the list on the tool page.

**Comment by roysmith** [comment]
Ah, I see.  The IP is the case name.  Got it, thanks.

**Comment by roysmith** [comment]
Ugh.  The problem is the "/" in the case name, which screws up URL handling, specifically calls to django.urls.reverse() in IndexView.post().  In theory, this could be handled, but it would be a lot of work to sort out every place we need to pass strings through quote() and unquote().

This blows things up on the wiki too.  The templates in https://en.wikipedia.org/wiki/Wikipedia:Sockpuppet_investigations/2605:E000:1F00:D3F1:0:0:0:0/64 think the case name is "64".

Probably more trouble than it's worth to fix correctly.  I'll probably just disallow case names with "/" in them.
